### ISSUE TITLE
How to use with events remote?

### ISSUE THREAD

**Issue by MrHOY** [lbertenasco/ap-ng2-fullcalendar#64]
When I change date or mode of calendar, I have to get events from API and render to calendar
my component:
```
calendarOption: object = {
 ...
 events: [],
 viewRender: (view, element) => {
  let param= {
   daystart: view.start.format(),
   dayend: view.end.format()
  }
  this.getData(param)
 }
 ...
}

ngOnInit(){}

onCalendarInit() {
  }

getData(param){
 this.calendarOption['events'] = []
 this.my_service.get(API, {params: param}).subscribe(
  data => {
   for(let item of data){
    let obj = {
     id: item.id,
     title: item.title,
     start: item.starttime
    }
    this.calendarOption['events'].push(item) // has data
   }
  } 
 )
}
```
But no events show on calendar, What I made wrong?

**Comment by lbertenasco** [comment]
Hi @MrHOY !
Can you please try with re-rendering the events afterwards?
https://fullcalendar.io/docs/event_rendering/rerenderEvents/

You can also use: https://fullcalendar.io/docs/event_data/events_function/

I'm closing the issue since it's not related to the npm-package, feel free to re-open if needed.
