### ISSUE TITLE
Trouble using methods on calendar events

### ISSUE THREAD

**Issue by PWinderl** [lbertenasco/ap-ng2-fullcalendar#73]
Hi,
I followed your instructions to set up my calendar and anything is working fine so far.
But now I want to remove events and don't know how to do so.

I`m not able to use the fullcalendar methods entirely.
My guess is that I didn't initiate and link the calendar right in the first place:

`export class MainCalComponent implements OnInit {

  private professorHoursListener;

  officeHoursProf;
  finalEvents = [];

  calendarOptions;

  myOfficeHour = {
    title: 'title',
    start: 'start',
    end: 'end',
    color: 'color'
  };

  @ViewChild(CalendarComponent) myCalendar: CalendarComponent;`

Because by interacting with the events the event-rendering works, but not to remove them:

`this.finalEvents.push(this.myOfficeHour);
this.myCalendar.fullCalendar('removeEvents', this.finalEvents);
    this.myCalendar.fullCalendar('renderEvents', this.finalEvents);`

my HTML looks like this:
`<angular2-fullcalendar [options]="calendarOptions" (initialized)="onCalendarInit($event)"></angular2-fullcalendar>
`

I would appreciate it a lot if you help me!

**Comment by lbertenasco** [comment]
Hi @PWinderl !
Please read the official fullcalendar documentation: https://fullcalendar.io/docs/event_data/removeEvents/

If you want to remove all events, you can just do `this.myCalendar.fullCalendar('removeEvents')`
If you want to remove certain items I sugget you use a filter function:
``` javascript
this.myCalendar.fullCalendar('removeEvents', (event) => {
  return this.checkIfEventShouldBeRemoved(event); // replace this logic with your own.
});
```
I'm closing this issue since it's not related to the package.
Feel free to reopen this issue.
